package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"fmt"

	"github.com/irlanteles/api-graphql/graph/model"
)

// Checklist is the resolver for the checklist field.
func (r *mutationResolver) Checklist(ctx context.Context, input model.ChecklistInput) (*model.ChecklistPayload, error) {
	id, err := r.ChecklistService.Criar(ctx, &input)
	if err != nil {
		return &model.ChecklistPayload{
			ID:       0,
			Mensagem: "Erro ao criar checklist: " + err.Error(),
			Status:   false,
		}, nil
	}

	return &model.ChecklistPayload{
		ID:       int32(id),
		Mensagem: "Checklist criado com sucesso",
		Status:   true,
	}, nil
}

// Checkout is the resolver for the checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, input model.CheckoutInput) (*model.CheckoutPayload, error) {
	id, err := r.CheckoutService.Criar(ctx, &input)
	if err != nil {
		return &model.CheckoutPayload{
			ID:       0,
			Mensagem: "Erro ao criar checkout: " + err.Error(),
			Status:   false,
		}, nil
	}

	return &model.CheckoutPayload{
		ID:       int32(id),
		Mensagem: "Checkout criado com sucesso",
		Status:   true,
	}, nil
}

// CriarViagem is the resolver for the criarViagem field.
func (r *mutationResolver) CriarViagem(ctx context.Context, input model.ViagemInput) (*model.ViagemPayload, error) {
	// Helper para desreferenciar *int32 com fallback 0
	ptrInt := func(v *int32) int {
		if v == nil {
			return 0
		}
		return int(*v)
	}
	// Helper para desreferenciar *string com fallback ""
	ptrStr := func(v *string) string {
		if v == nil {
			return ""
		}
		return *v
	}

	err := r.ViagemService.CriarViagem(
		ctx,
		int(input.SolicitacaoSolicitante),
		input.SolicitacaoQtdpessoa,
		int(input.TipoVeiculoID),
		input.Enderecos,
		ptrStr(input.SolicitacaoRoteiroDs),
		ptrStr(input.SolicitacaoObs),
		input.SolicitacaoDt,
		ptrStr(input.SolicitacaoHr),
		ptrStr(input.SolicitacaoSaidaDtPrevista),
		ptrStr(input.SolicitacaoRetornoDtPrevista),
		ptrInt(input.SolicitacaoUnidadecusto),
		ptrInt(input.SolicitacaoSituacao),
		ptrInt(input.SolicitacaoSt),
		ptrStr(input.SolicitacaoDtCriacao),
		ptrInt(input.SolicitacaoSolicitanteEst),
		ptrInt(input.ProjetoCd),
		ptrInt(input.AcaoCd),
		ptrInt(input.TerritorioCd),
		ptrInt(input.FonteCd),
		ptrStr(input.SolicitacaoNumero),
		int(input.QuantidadePessoa),
		func(in []int32) []int {
			out := make([]int, len(in))
			for i, v := range in {
				out[i] = int(v)
			}
			return out
		}(input.PassageiroIds),
		int(input.Ordem),
	)

	if err != nil {
		return &model.ViagemPayload{
			Mensagem: "Erro ao criar viagem: " + err.Error(),
			Status:   false,
		}, nil
	}

	return &model.ViagemPayload{
		Mensagem: "Viagem criada com sucesso",
		Status:   true,
	}, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context, idMotorista int32) (*model.Dashboard, error) {
	d, err := r.DashboardService.ObterDashboard(ctx, fmt.Sprintf("%d", idMotorista))
	if err != nil {
		return nil, err
	}

	viagens := make([]*model.ViagemDashboard, len(d.Viagens))
	for i, v := range d.Viagens {
		paradas := make([]*model.Parada, len(v.Paradas))
		for j, p := range v.Paradas {
			paradas[j] = &model.Parada{
				Data:        p.Data,
				Horario:     p.Horario,
				Solicitante: p.Solicitante,
				Autorizado:  p.Autorizado,
				Origem:      p.Origem,
				Destino:     p.Destino,
				Placa:       p.Placa,
			}
		}
		viagens[i] = &model.ViagemDashboard{
			NumeroSolicitacao: v.NumeroSolicitacao,
			Paradas:           paradas,
		}
	}

	return &model.Dashboard{
		Motorista: &model.Motorista{
			ID:    d.Motorista.ID,
			Nome:  d.Motorista.Nome,
			Placa: d.Motorista.Placa,
		},
		Viagens: viagens,
	}, nil
}

// Veiculos is the resolver for the veiculos field.
func (r *queryResolver) Veiculos(ctx context.Context) ([]*model.Veiculo, error) {
	return r.VeiculoService.ListarVeiculos(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
