// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChecklistInput struct {
	IDSolicitacao     int32    `json:"id_solicitacao"`
	LimpezaExterior   *int32   `json:"limpeza_exterior,omitempty"`
	ExteriorDetalhes  *string  `json:"exterior_detalhes,omitempty"`
	LimpezaInterior   *int32   `json:"limpeza_interior,omitempty"`
	InteriorDetalhes  *string  `json:"interior_detalhes,omitempty"`
	NivelOleoMotor    *int32   `json:"nivel_oleo_motor,omitempty"`
	NivelOleoDirecao  *int32   `json:"nivel_oleo_direcao,omitempty"`
	NivelOleoFreio    *int32   `json:"nivel_oleo_freio,omitempty"`
	NivelAguaRadiador *int32   `json:"nivel_agua_radiador,omitempty"`
	Combustivel       *int32   `json:"combustivel,omitempty"`
	Lampadas          *int32   `json:"lampadas,omitempty"`
	ChaveRoda         *int32   `json:"chave_roda,omitempty"`
	Macaco            *int32   `json:"macaco,omitempty"`
	Triangulo         *int32   `json:"triangulo,omitempty"`
	Extintor          *int32   `json:"extintor,omitempty"`
	Tapetes           *int32   `json:"tapetes,omitempty"`
	NivelCombustivel  *float64 `json:"nivel_combustivel,omitempty"`
	Estepe            *int32   `json:"estepe,omitempty"`
	Observacoes       *string  `json:"observacoes,omitempty"`
	Status            *int32   `json:"status,omitempty"`
	Buzina            *int32   `json:"buzina,omitempty"`
	Placa             *string  `json:"placa,omitempty"`
	DataHoraReal      *string  `json:"data_hora_real,omitempty"`
	Setas             *int32   `json:"setas,omitempty"`
	Tipo              *int32   `json:"tipo,omitempty"`
}

type ChecklistPayload struct {
	ID       int32  `json:"id"`
	Mensagem string `json:"mensagem"`
	Status   bool   `json:"status"`
}

type CheckoutInput struct {
	IDSolicitacao       int32    `json:"id_solicitacao"`
	LimpezaExterior     *int32   `json:"limpeza_exterior,omitempty"`
	ExteriorDetalhes    *string  `json:"exterior_detalhes,omitempty"`
	LimpezaInterior     *int32   `json:"limpeza_interior,omitempty"`
	InteriorDetalhes    *string  `json:"interior_detalhes,omitempty"`
	NivelOleoMotor      *int32   `json:"nivel_oleo_motor,omitempty"`
	NivelOleoDirecao    *int32   `json:"nivel_oleo_direcao,omitempty"`
	NivelOleoFreio      *int32   `json:"nivel_oleo_freio,omitempty"`
	NivelAguaRadiador   *int32   `json:"nivel_agua_radiador,omitempty"`
	Combustivel         *int32   `json:"combustivel,omitempty"`
	Lampadas            *int32   `json:"lampadas,omitempty"`
	ChaveRoda           *int32   `json:"chave_roda,omitempty"`
	Macaco              *int32   `json:"macaco,omitempty"`
	Triangulo           *int32   `json:"triangulo,omitempty"`
	Extintor            *int32   `json:"extintor,omitempty"`
	Tapetes             *int32   `json:"tapetes,omitempty"`
	NivelCombustivel    *float64 `json:"nivel_combustivel,omitempty"`
	Estepe              *int32   `json:"estepe,omitempty"`
	Observacoes         *string  `json:"observacoes,omitempty"`
	Status              *int32   `json:"status,omitempty"`
	Buzina              *int32   `json:"buzina,omitempty"`
	Placa               *string  `json:"placa,omitempty"`
	DataHoraReal        *string  `json:"data_hora_real,omitempty"`
	Setas               *int32   `json:"setas,omitempty"`
	Ocorrencia          *int32   `json:"ocorrencia,omitempty"`
	Acidente            *int32   `json:"acidente,omitempty"`
	Barulho             *int32   `json:"barulho,omitempty"`
	Motor               *int32   `json:"motor,omitempty"`
	DescricaoIncidentes *string  `json:"descricao_incidentes,omitempty"`
	Pneus               *int32   `json:"pneus,omitempty"`
	NiveisFluidos       *int32   `json:"niveis_fluidos,omitempty"`
}

type CheckoutPayload struct {
	ID       int32  `json:"id"`
	Mensagem string `json:"mensagem"`
	Status   bool   `json:"status"`
}

type Dashboard struct {
	Motorista *Motorista         `json:"motorista"`
	Viagens   []*ViagemDashboard `json:"viagens"`
}

type Motorista struct {
	ID   *int32 `json:"id,omitempty"`
	Nome string `json:"nome"`
}

type Mutation struct {
}

type Parada struct {
	RoteiroID     int32  `json:"roteiroId"`
	DataInicio    string `json:"dataInicio"`
	HorarioInicio string `json:"horarioInicio"`
	DataFinal     string `json:"dataFinal"`
	HorarioFinal  string `json:"horarioFinal"`
	Ordem         int32  `json:"ordem"`
	Solicitante   string `json:"solicitante"`
	Autorizado    string `json:"autorizado"`
	Origem        string `json:"origem"`
	Destino       string `json:"destino"`
}

type Passageiro struct {
	PessoaID          int32  `json:"pessoa_id"`
	PessoaNm          string `json:"pessoa_nm"`
	SolicitacaoID     int32  `json:"solicitacao_id"`
	PassageiroSt      int32  `json:"passageiro_st"`
	SolicitacaoNumero string `json:"solicitacao_numero"`
}

type Query struct {
}

type Solicitacao struct {
	SolicitacaoID          int32   `json:"solicitacao_id"`
	SolicitacaoSituacao    *int32  `json:"solicitacao_situacao,omitempty"`
	SolicitacaoSaidaDt     *string `json:"solicitacao_saida_dt,omitempty"`
	SolicitacaoRetornoDt   *string `json:"solicitacao_retorno_dt,omitempty"`
	SolicitacaoSt          *int32  `json:"solicitacao_st,omitempty"`
	SolicitacaoKminicial   *string `json:"solicitacao_kminicial,omitempty"`
	SolicitacaoKmfinal     *string `json:"solicitacao_kmfinal,omitempty"`
	SolicitacaoDtAlteracao *string `json:"solicitacao_dt_alteracao,omitempty"`
}

type UpdateRoteiroInput struct {
	RoteiroID      int32   `json:"roteiro_id"`
	RoteiroSt      *int32  `json:"roteiro_st,omitempty"`
	DataHoraInicio *string `json:"data_hora_inicio,omitempty"`
	DataHoraFim    *string `json:"data_hora_fim,omitempty"`
}

type UpdateRoteiroPayload struct {
	Mensagem string `json:"mensagem"`
	Status   bool   `json:"status"`
}

type UpdateSolicitacaoInput struct {
	SolicitacaoID        int32   `json:"solicitacao_id"`
	SolicitacaoSituacao  *int32  `json:"solicitacao_situacao,omitempty"`
	SolicitacaoSaidaDt   *string `json:"solicitacao_saida_dt,omitempty"`
	SolicitacaoRetornoDt *string `json:"solicitacao_retorno_dt,omitempty"`
	SolicitacaoSt        *int32  `json:"solicitacao_st,omitempty"`
	SolicitacaoKminicial *string `json:"solicitacao_kminicial,omitempty"`
	SolicitacaoKmfinal   *string `json:"solicitacao_kmfinal,omitempty"`
}

type UpdateSolicitacaoPayload struct {
	Mensagem    string       `json:"mensagem"`
	Status      bool         `json:"status"`
	Solicitacao *Solicitacao `json:"solicitacao,omitempty"`
}

type Veiculo struct {
	VeiculoID                int32   `json:"veiculo_id"`
	VeiculoPlaca             string  `json:"veiculo_placa"`
	TipoVeiculoID            int32   `json:"tipo_veiculo_id"`
	VeiculoSt                int32   `json:"veiculo_st"`
	VeiculoDtCriacao         *string `json:"veiculo_dt_criacao,omitempty"`
	VeiculoTag               *string `json:"veiculo_tag,omitempty"`
	PessoaID                 *int32  `json:"pessoa_id,omitempty"`
	HodometroInicial         *int32  `json:"hodometro_inicial,omitempty"`
	HodometroFinal           *int32  `json:"hodometro_final,omitempty"`
	TipoVeiculoDs            *string `json:"tipo_veiculo_ds,omitempty"`
	TipoVeiculoQtdPassageiro int32   `json:"tipo_veiculo_qtd_passageiro"`
}

type ViagemDashboard struct {
	SolicitacaoID     int32     `json:"solicitacaoId"`
	NumeroSolicitacao string    `json:"numeroSolicitacao"`
	RoteiroDs         *string   `json:"roteiroDs,omitempty"`
	Paradas           []*Parada `json:"paradas"`
}

type ViagemInput struct {
	SolicitacaoSolicitante       int32    `json:"solicitacao_solicitante"`
	SolicitacaoQtdpessoa         string   `json:"solicitacao_qtdpessoa"`
	TipoVeiculoID                int32    `json:"tipo_veiculo_id"`
	Enderecos                    []string `json:"enderecos"`
	SolicitacaoRoteiroDs         *string  `json:"solicitacao_roteiro_ds,omitempty"`
	SolicitacaoObs               *string  `json:"solicitacao_obs,omitempty"`
	SolicitacaoDt                string   `json:"solicitacao_dt"`
	SolicitacaoHr                *string  `json:"solicitacao_hr,omitempty"`
	SolicitacaoSaidaDtPrevista   *string  `json:"solicitacao_saida_dt_prevista,omitempty"`
	SolicitacaoRetornoDtPrevista *string  `json:"solicitacao_retorno_dt_prevista,omitempty"`
	SolicitacaoUnidadecusto      *int32   `json:"solicitacao_unidadecusto,omitempty"`
	SolicitacaoSituacao          *int32   `json:"solicitacao_situacao,omitempty"`
	SolicitacaoSt                *int32   `json:"solicitacao_st,omitempty"`
	SolicitacaoDtCriacao         *string  `json:"solicitacao_dt_criacao,omitempty"`
	SolicitacaoSolicitanteEst    *int32   `json:"solicitacao_solicitante_est,omitempty"`
	ProjetoCd                    *int32   `json:"projeto_cd,omitempty"`
	AcaoCd                       *int32   `json:"acao_cd,omitempty"`
	TerritorioCd                 *int32   `json:"territorio_cd,omitempty"`
	FonteCd                      *int32   `json:"fonte_cd,omitempty"`
	SolicitacaoNumero            *string  `json:"solicitacao_numero,omitempty"`
	QuantidadePessoa             int32    `json:"quantidade_pessoa"`
	PassageiroIds                []int32  `json:"passageiro_ids"`
	Ordem                        int32    `json:"ordem"`
}

type ViagemPayload struct {
	Mensagem string `json:"mensagem"`
	Status   bool   `json:"status"`
}
